version: '3.3'

services:
  ninder:
    image: 'ghcr.io/marcel-lambacher/ninder/ninder:latest'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ninder.rule=Host(`ninder.marcel-lambacher.de`)'
      - 'traefik.http.routers.ninder.entrypoints=websecure'
      - 'traefik.http.routers.ninder.tls.certresolver=myresolver'
    ports:
      - mode: ingress
        target: 3000
        published: 3002
        protocol: tcp
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FIREBASE_ADMIN_CREDENTIALS=${FIREBASE_ADMIN_CREDENTIALS}
    deploy:
      replicas: 1
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
