name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env File
        run: |
          echo "DB_USER: ${{ secrets.DB_USER }}" >> .env
          echo "DB_HOST: ${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME: ${{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT: ${{ secrets.DB_PORT }}" >> .env
          echo "FIREBASE_ADMIN_CREDENTIALS: ${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}" >> .env

      - name: Create .env File
        run: |
          echo "DB_USER: ${{ secrets.DB_USER }}" >> hello.txt
          echo "DB_HOST: ${{ secrets.DB_HOST }}" >> hello.txt
          echo "DB_NAME: ${{ secrets.DB_NAME }}" >> hello.txt
          echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}" >> hello.txt
          echo "DB_PORT: ${{ secrets.DB_PORT }}" >> hello.txt
          echo "FIREBASE_ADMIN_CREDENTIALS: ${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}" >> hello.txt

      - name: Log content to the Actions log
        run: |
          echo "Logging content to GitHub Actions log:"
          cat .env

      - name: List files again to confirm .env creation
        run: |
          ls -la

      - name: Save file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env
          path: hello.txt

   # Install Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Docker Registry
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          export REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          export IMAGE_NAME=ghcr.io/$REPO_NAME/ninder
          export COMMIT_HASH=$(git rev-parse --short HEAD)
          docker buildx build \
            --platform linux/arm64 \
            --tag $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:$COMMIT_HASH \
            --push .